// Regression guard for the hSigL meson-sector δ-closed-loop collapse
// (see the σL δ-closed quark loop in tests/gen/gen_sigl_dirac.wls).
//
// The σL (scalar) component of the quark self-energy is projected by the spinor IDENTITY δ[d1,d2],
// so a meson-exchange quark loop threading two pion γ5 vertices is closed by a BARE spinor δ sitting
// INSIDE the Dirac chain: tr(δ · γ5 · S · γ5 · S) = tr(γ5·(γ·l1)·γ5·(γ·p1)) ∝ l1·p1 ≠ 0.
//
// The old orderDiracFacs walked the spinor loop with a DIRECTED forward map; the symmetric external δ
// collided on the shared in/out keys and broke the walk, collapsing the trace to a single γ5 →
// tr(γ5)=0 → the whole diagram vanished. The fixed walk is undirected and closes the cycle. The net
// is hand-built (no FunKit/FORM), so the independent reference is the closed form evaluated by hand
// over the propFrame kinematics, computed with the SAME regulator the kernel bakes in:
//
//   tr(1/4 · δ · γ5·(-I)(γ·l1)G(l1)·γ5·(-I)(γ·p1)G(p1)) = (l1·p1) · G(l1^2) · G(p^2)
//   propFrame(p, l1, cos1):  p1 = p{1,0,0,0},  l1vec = l1{cos1, sqrt(1-cos1^2), 0, 0}
//   so l1·p1 = l1·p·cos1,   G(x) = 1/(x + RF(k^2, x))
// Pre-fix the numeric trace collapsed to ≈0; post-fix it matches the (non-vanishing) closed form,
// guarding against a silent re-collapse. Generated by gen/gen_sigl_dirac.wls.
// The kernel calls RF unqualified and gets it from nt_regulators.hpp, which its generator lists in
// "ExtraIncludes" — so the oracle below reads the SAME RF from there rather than defining its own
// (any consistent RF validates the trace; what matters is that both sides use one definition).
#include "Sigl_dirac_num_kernel.hh" // numeric kernel (gen/), pulls in nt_regulators.hpp

#include <cmath>
#include <cstdio>
#include <random>

namespace {
// baked closed-form fermion dressing G(q^2) = 1 / (q^2 + RF(k^2, q^2))
double G(double q2, double k) { return 1.0 / (q2 + ::RF(k * k, q2)); }

double oracle(double l1, double cos1, double p, double k)
{
  const double LdotP = l1 * p * cos1;      // l1vec · p1 (Euclidean)
  return LdotP * G(l1 * l1, k) * G(p * p, k);
}
} // namespace

int main() {
  using Num = Sigl_dirac_num_kernel;

  std::mt19937 rng(2024);
  std::uniform_real_distribution<double> ul(0.1, 4.0), uk(0.3, 3.0), uc(-0.99, 0.99);
  double maxRel = 0.0, maxAbs = 0.0;
  const int N = 40000;
  for (int i = 0; i < N; ++i) {
    const double l1 = ul(rng), k = uk(rng), p = ul(rng), cos1 = uc(rng);
    const double a = oracle(l1, cos1, p, k);
    const double iv = Num::kernel(l1, cos1, p, k);
    maxRel = std::max(maxRel, std::fabs(a - iv) / (1e-300 + std::fabs(a)));
    maxAbs = std::max(maxAbs, std::fabs(a));
  }

  std::printf("[σL δ-closed meson quark loop — tr(δ·γ5·S·γ5·S), the orderDiracFacs δ-closure guard]\n");
  std::printf("  analytic vs numeric max rel err = %.3e  (numeric = gamma-trace theorem)\n", maxRel);
  std::printf("  max |analytic|             = %.3e  (non-vanishing δ-closed trace ∝ l1·p1)\n", maxAbs);

  // the trace must NOT be identically zero — that is exactly the bug (a collapsed single-γ5 walk).
  const bool ok = maxRel < 1e-11 && maxAbs > 1e-6;
  std::printf("\n%s\n", ok ? "ALL TESTS PASSED" : "TESTS FAILED");
  return ok ? 0 : 1;
}
